language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - cd ext/forp
    - phpize && ./configure && make && sudo make install
    - echo "extension=forp.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: php -f forp.php
